name: Deploy Documentation

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev libsdl2-dev mesa-utils

      - name: Build documentation
        run: cargo doc --no-deps --document-private-items --all-features
        working-directory: engine-src

      - name: Create redirect index file
        run: |
          CRATE_NAME=$(grep '^name =' Cargo.toml | head -n1 | sed -E 's/name = "(.*)"/\1/' | tr '[:upper:]' '[:lower:]')
          echo "<meta http-equiv=\"refresh\" content=\"0; url=${CRATE_NAME}\">" > target/doc/index.html
        working-directory: engine-src

      - name: Deploy to different repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: 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
          publish_dir: engine-src/target/doc
          external_repository: RedddFoxxyy/Terra-Engine-Docs
